version: '3.8'
services:
  postgre:
    image: postgres
    restart: always
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgres

    networks:
      - postgres-network


volumes:
  postgres:

networks:
  postgres-network:
